import { ACTIVITY_CATEGORIES, getActivityCategoryByLabel } from '@/constants/activity-categories';
import { ActivityFilter, EventItem } from '@/components/home/types';

export const activityFilters: ActivityFilter[] = ACTIVITY_CATEGORIES;

export const featuredEvents: EventItem[] = [
  {
    id: 'event-1',
    title: 'Sunrise Run & Matcha',
    dateTimeIso: '2026-04-01T07:00:00.000Z',
    category: 'Run',
    activityType: 'Run',
    time: 'Today, 7:00 AM',
    dateLabel: 'Today',
    timeLabel: '7:00 AM',
    location: 'Moda Coast Trail',
    description: 'A breezy sunrise run followed by matcha and easy conversation by the water.',
    notes: 'Bring running shoes and a light layer. We will keep the pace conversational.',
    hostId: 'user-lina-park',
    hostName: 'Lina Park',
    hostInitials: 'LP',
    hostBio: 'Early riser, consistent host, and always the first to share the route plan.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',
    participantCount: 8,
    participantLimit: 10,
    participants: [
      { id: 'event-1-participant-1', userId: 'user-lina-park', name: 'Lina Park', initials: 'LP', rating: 4.9 },
      { id: 'event-1-participant-2', userId: 'user-maya-ceylan', name: 'Maya Ceylan', initials: 'MC', rating: 4.3 },
      { id: 'event-1-participant-3', userId: 'user-noah-chen', name: 'Noah Chen', initials: 'NC', rating: 4.7 },
      { id: 'event-1-participant-4', userId: 'user-aylin-demir', name: 'Aylin Demir', initials: 'AD', rating: 4.8 },
    ],
    privacyType: 'Public',
    rating: 4.9,
    accentColor: getActivityCategoryByLabel('Run').color,
  },
  {
    id: 'event-2',
    title: 'Neighborhood Coffee Swap',
    dateTimeIso: '2026-04-01T11:30:00.000Z',
    category: 'Coffee',
    activityType: 'Coffee',
    time: 'Today, 11:30 AM',
    dateLabel: 'Today',
    timeLabel: '11:30 AM',
    location: 'Karakoy Roasters',
    description: 'Bring a favorite bean recommendation and trade cafe notes with the group.',
    notes: 'A small group table is reserved inside. Feel free to bring a notebook or book recommendation.',
    hostId: 'user-emir-demir',
    hostName: 'Emir Demir',
    hostInitials: 'ED',
    hostBio: 'Known for warm intros, thoughtful pacing, and very good coffee lists.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80',
    participantCount: 6,
    participantLimit: 8,
    participants: [
      { id: 'event-2-participant-1', userId: 'user-emir-demir', name: 'Emir Demir', initials: 'ED', rating: 4.8 },
      { id: 'event-2-participant-2', userId: 'user-lena-hart', name: 'Lena Hart', initials: 'LH', rating: 4.7 },
      { id: 'event-2-participant-3', userId: 'user-theo-park', name: 'Theo Park', initials: 'TP', rating: 4.6 },
    ],
    privacyType: 'Invite-only',
    rating: 4.8,
    accentColor: getActivityCategoryByLabel('Coffee').color,
  },
  {
    id: 'event-3',
    title: 'After-Work Padel Rally',
    dateTimeIso: '2026-04-01T18:45:00.000Z',
    category: 'Sport',
    activityType: 'Sport',
    time: 'Today, 6:45 PM',
    dateLabel: 'Today',
    timeLabel: '6:45 PM',
    location: 'Maçka Courts',
    description: 'Friendly padel sets after work with space for all skill levels.',
    notes: 'Bring water and comfortable court shoes. Teams rotate every set.',
    hostId: 'user-nora-chen',
    hostName: 'Nora Chen',
    hostInitials: 'NC',
    hostBio: 'Reliable sports host who keeps sessions social, organized, and beginner-friendly.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80',
    participantCount: 10,
    participantLimit: 10,
    participants: [
      { id: 'event-3-participant-1', userId: 'user-nora-chen', name: 'Nora Chen', initials: 'NC', rating: 4.7 },
      { id: 'event-3-participant-2', userId: 'user-omar-kaya', name: 'Omar Kaya', initials: 'OK', rating: 4.8 },
      { id: 'event-3-participant-3', userId: 'user-mina-ates', name: 'Mina Ates', initials: 'MA', rating: 4.6 },
      { id: 'event-3-participant-4', userId: 'user-theo-park', name: 'Theo Park', initials: 'TP', rating: 4.6 },
    ],
    privacyType: 'Private',
    rating: 4.7,
    accentColor: getActivityCategoryByLabel('Sport').color,
  },
  {
    id: 'event-4',
    title: 'Rooftop Games & Good Talk',
    dateTimeIso: '2026-04-02T20:00:00.000Z',
    category: 'Food',
    activityType: 'Food',
    time: 'Tomorrow, 8:00 PM',
    dateLabel: 'Tomorrow',
    timeLabel: '8:00 PM',
    location: 'Cihangir Terrace',
    description: 'Card games, rooftop snacks, and a relaxed crowd for a low-key evening.',
    notes: 'Hosted on a private terrace with a curated guest list and light snacks.',
    hostId: 'user-mert-kaya',
    hostName: 'Mert Kaya',
    hostInitials: 'MK',
    hostBio: 'Hosts low-pressure evenings with great pacing and a welcoming, respectful crowd.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80',
    participantCount: 12,
    participantLimit: 14,
    participants: [
      { id: 'event-4-participant-1', userId: 'user-mert-kaya', name: 'Mert Kaya', initials: 'MK', rating: 4.9 },
      { id: 'event-4-participant-2', userId: 'user-aylin-demir', name: 'Aylin Demir', initials: 'AD', rating: 4.8 },
      { id: 'event-4-participant-3', userId: 'user-lina-park', name: 'Lina Park', initials: 'LP', rating: 4.9 },
    ],
    privacyType: 'Public',
    rating: 4.9,
    accentColor: getActivityCategoryByLabel('Food').color,
  },
  {
    id: 'event-7',
    title: 'Board Game Night in Cihangir',
    dateTimeIso: '2026-04-03T19:30:00.000Z',
    category: 'Games',
    activityType: 'Games',
    time: 'Fri, 7:30 PM',
    dateLabel: 'Fri',
    timeLabel: '7:30 PM',
    location: 'Cihangir Living Room',
    description: 'A friendly board game night with easy icebreakers, team games, and a small trusted group.',
    notes: 'We will rotate through light strategy and social games. Newcomers are very welcome.',
    hostId: 'user-theo-park',
    hostName: 'Theo Park',
    hostInitials: 'TP',
    hostBio: 'Keeps group games welcoming, organized, and easy to join even if you do not know anyone yet.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=900&q=80',
    participantCount: 5,
    participantLimit: 8,
    participants: [
      { id: 'event-7-participant-1', userId: 'user-theo-park', name: 'Theo Park', initials: 'TP', rating: 4.6 },
      { id: 'event-7-participant-2', userId: 'user-lena-hart', name: 'Lena Hart', initials: 'LH', rating: 4.7 },
      { id: 'event-7-participant-3', userId: 'user-noah-chen', name: 'Noah Chen', initials: 'NC', rating: 4.7 },
    ],
    privacyType: 'Public',
    rating: 4.6,
    accentColor: getActivityCategoryByLabel('Games').color,
  },
];

const additionalActivityHubEvents: EventItem[] = [
  {
    id: 'event-5',
    title: 'Seaside Reading Circle',
    dateTimeIso: '2026-03-18T18:30:00.000Z',
    category: 'Reading',
    activityType: 'Reading',
    time: 'Wed, Mar 18 • 18:30',
    dateLabel: 'Wed, Mar 18',
    timeLabel: '18:30',
    location: 'Caddebostan Coast',
    description: 'A relaxed reading session with tea, quiet conversation, and a small circle of regulars.',
    notes: 'Bring your current book and something warm. We usually read for 45 minutes before chatting.',
    hostId: 'user-maya-ceylan',
    hostName: 'Maya Ceylan',
    hostInitials: 'MC',
    hostBio: 'Thoughtful host for calm, well-paced meetups where people can settle in quickly.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80',
    participantCount: 5,
    participantLimit: 6,
    participants: [
      { id: 'event-5-participant-1', userId: 'user-maya-ceylan', name: 'Maya Ceylan', initials: 'MC', rating: 4.3 },
      { id: 'event-5-participant-2', userId: 'user-lena-hart', name: 'Lena Hart', initials: 'LH', rating: 4.7 },
      { id: 'event-5-participant-3', userId: 'user-emir-demir', name: 'Emir Demir', initials: 'ED', rating: 4.8 },
    ],
    privacyType: 'Public',
    rating: 4.6,
    accentColor: getActivityCategoryByLabel('Reading').color,
  },
  {
    id: 'event-6',
    title: 'Studio Stretch Session',
    dateTimeIso: '2026-03-10T19:00:00.000Z',
    category: 'Wellness',
    activityType: 'Wellness',
    time: 'Tue, Mar 10 • 19:00',
    dateLabel: 'Tue, Mar 10',
    timeLabel: '19:00',
    location: 'Nisantasi Flow Studio',
    description: 'A gentle post-work mobility class with a calm host and a small group.',
    notes: 'Open to all levels. Mats are available in the studio.',
    hostId: 'user-mina-ates',
    hostName: 'Mina Ates',
    hostInitials: 'MA',
    hostBio: 'Warm and encouraging host who likes creating low-pressure wellness routines.',
    hostPhotoUrl:
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    participantCount: 7,
    participantLimit: 10,
    participants: [
      { id: 'event-6-participant-1', userId: 'user-mina-ates', name: 'Mina Ates', initials: 'MA', rating: 4.6 },
      { id: 'event-6-participant-2', userId: 'user-maya-ceylan', name: 'Maya Ceylan', initials: 'MC', rating: 4.3 },
      { id: 'event-6-participant-3', userId: 'user-aylin-demir', name: 'Aylin Demir', initials: 'AD', rating: 4.8 },
    ],
    privacyType: 'Public',
    rating: 4.5,
    accentColor: getActivityCategoryByLabel('Wellness').color,
  },
];

export const allEvents = [...featuredEvents, ...additionalActivityHubEvents];

export function getFeaturedEventById(id: string) {
  return allEvents.find((event) => event.id === id);
}
